### PR TITLE
Adding OrangePi5

### PR DESCRIPTION
**Pull request by alexeyatbluescape**
I have tested this overlaying rendered model over my 3d mock. Looks great.

Screenshot 2023-02-21 at 11 54 52 PM

Had to improvise and some components were missing.

### CODE REVIEW

**Comment by alexeyatbluescape** [comment]
Renders:
Screenshot 2023-02-22 at 12 05 50 AM
Screenshot 2023-02-22 at 12 06 01 AM

**Review by ProKn1fe — COMMENTED** [review]
LGTM!

**Review by hominoids — APPROVED** [review]
Looks good.

**Comment by hominoids** [comment]
Thank you for your work on the OrangePi 5 model.

**Pull request merged**
